Instructions/Azure AD Identity Protection (az-101-04b).md, Instructions/Implement ASR Between Regions (az-101-01).md, Instructions/Implement Directory Synchronization (az-100-05).md, Instructions/Implementing File Sync (az-100-02b).md, Instructions/Load Balancer and Traffic Manager (az-101-03).md, Instructions/Privileged Identity Management (az-101-04).md, Instructions/Role-Based Access Control (az-100-01).md, Instructions/Self-Service Password Reset (az-100-05b).md, Instructions/VNet Peering and Service Chaining (az-100-04).md
corrected some typos and syntax errors
=> found some typos and syntax errors

LICENSE
This license file is required for all Microsoft repositories
=> Added standard license file

Instructions/Labs/Deploy and Manage Virtual Machines (az-100-03).md
=> Changed link as it was not working .

Instructions/Labs/Privileged Identity Management (az-101-04).md
In task 1 (exercise 0), in the tittle we make reference to "Windows Server" but the JSON template deploys Ubuntu.
=> Fixing for an error in the OS to deploy

Instructions/Labs/Governance and Compliance (az-100-01b).md
Now the policy is called "Required tag … " and not "Enforce tag … "
=> change in the policy definition

Instructions/Labs/02a - Deploy and Manage Virtual Machines (az-100-03).md, Instructions/Labs/02b - Virtual Machines and Scale Sets (az-100-03b).md, Instructions/Labs/03 - Implement and Manage Storage (az-100-02).md, Instructions/Labs/04 - Configure Azure DNS (az-100-04b).md, Instructions/Labs/06 - Azure Network Watcher (az-101-03b).md, Instructions/Labs/09 - Implement Directory Synchronization (az-100-05).md, Instructions/Labs/11a - Role-Based Access Control (az-100-01).md, Instructions/Labs/11b - Governance and Compliance (az-100-01b).md, Instructions/Labs/Optional - Azure Event Grid and Azure Logic Apps (az-101-02b).md, Instructions/Labs/Optional - Implement and Manage Azure Web Apps (az-101-02).md, Instructions/Labs/Optional - Migrate On-premises Hyper-V VMs to Azure (az-101-01b).md, Instructions/Labs/Optional - Privileged Identity Management (az-101-04).md
Updating Lab02a to use Az instead of AzureRM
Update all labs to point to the latest version of documentation
=> Fix Install powershell module 

Instructions/Labs/02a - Deploy and Manage Virtual Machines (az-100-03).md
Get-AzResource does not give Sku info, so use Use Get-AzDisk instead
Fix instructions to point to IP Configurations blade
=> Fix an error and a cosmetic improvement. 

Instructions/Labs/03 - Implement and Manage Storage (az-100-02).md
Typo: the cloud shell command should refer to a 203 destination, instead of a 302 destination. That's the folder that should be verified two steps later.
=> Update 03 - Implement and Manage Storage (az-100-02).md

Instructions/Labs/02a - Deploy and Manage Virtual Machines (az-100-03).md, Instructions/Labs/02b - Virtual Machines and Scale Sets (az-100-03b).md, Instructions/Labs/03 - Implement and Manage Storage (az-100-02).md, Instructions/Labs/04 - Configure Azure DNS (az-100-04b).md, Instructions/Labs/05 - VNet Peering and Service Chaining (az-100-04).md, Instructions/Labs/06 - Azure Network Watcher (az-101-03b).md, Instructions/Labs/09 - Implement Directory Synchronization (az-100-05).md, Instructions/Labs/11a - Role-Based Access Control (az-100-01).md, Instructions/Labs/11b - Governance and Compliance (az-100-01b).md, Instructions/Labs/Optional - Azure Event Grid and Azure Logic Apps (az-101-02b).md, Instructions/Labs/Optional - Implement and Manage Azure Web Apps (az-101-02).md, Instructions/Labs/Optional - Migrate On-premises Hyper-V VMs to Azure (az-101-01b).md, Instructions/Labs/Optional - Privileged Identity Management (az-101-04).md
This change helps improve the readability of the instruction on GitHub or other markdown renders with syntax highlight supports!
=> Enable syntax highlight in Instructions

Allfiles/Labfiles/AZ-100.2/az-100-02_azuredeploy.parameters.json, Allfiles/Labfiles/AZ-100.3/az-100-03_azuredeploy.json, Allfiles/Labfiles/AZ-100.3/az-100-03b_01_azuredeploy.parameters.json, Allfiles/Labfiles/AZ-100.3/az-100-03b_02_azuredeploy.parameters.json, Allfiles/Labfiles/AZ-100.4/az-100-04_01_azuredeploy.json, Allfiles/Labfiles/AZ-100.4/az-100-04_02_azuredeploy.json, Allfiles/Labfiles/AZ-101.3/az-101-03b_01_azuredeploy.parameters.json, Allfiles/Labfiles/AZ-101.3/az-101-03b_02_azuredeploy.parameters.json, Instructions/Labs/02a - Deploy and Manage Virtual Machines (az-100-03).md, Instructions/Labs/02b - Virtual Machines and Scale Sets (az-100-03b).md, Instructions/Labs/03 - Implement and Manage Storage (az-100-02).md, Instructions/Labs/04 - Configure Azure DNS (az-100-04b).md, Instructions/Labs/05 - VNet Peering and Service Chaining (az-100-04).md, Instructions/Labs/06 - Azure Network Watcher (az-101-03b).md
Addresses 53, 45, and 20 from Issues for Labs 1-6.
Also general fixes for latest version of portal.
=> General updates

Instructions/Labs/11b - Governance and Compliance (az-100-01b).md
Updated name of policy definition 'Enforce tag and its value' to 'Require tag and its value' to match the naming in Azure Portal as of 26th June 19
=> Update 11b - Governance and Compliance (az-100-01b).md

Instructions/Labs/07 - Implement ASR Between Regions (az-101-01).md
'Enabling replication' in the lab vs "enabling protection" on the portal
=> Exercice 2 - Task2

Instructions/Labs/07 - Implement ASR Between Regions (az-101-01).md, Instructions/Labs/09 - Implement Directory Synchronization (az-100-05).md, Instructions/Labs/10 - Azure AD Identity Protection (az-101-04b).md, Instructions/Labs/11a - Role-Based Access Control (az-100-01).md, Instructions/Labs/11b - Governance and Compliance (az-100-01b).md
Lots of changes that came about from the final two days I took this class.
One item that seemed to be a recurring issue was a lack of clean-up exercises after each module was completed.  This often led to quota limits being reached from various students in our class at various times.
=> Az103 class feedback

Instructions/Labs/02a - Deploy and Manage Virtual Machines (az-100-03).md
Added [smalldisk] to software plan choice to align with image selection
=> Added [smalldisk]

Instructions/Labs/02b - Virtual Machines and Scale Sets (az-100-03b).md
Updated the steps for selecting "Create Disk" to include the dropdown menu under "Name"
Added a "Save" step when adding VM disks
Added a "Save" step when scaling VM instances
=> Interface clarifications

Allfiles/Labfiles/Module_02/Virtual_Machines_and_Scale_Sets/az-100-03b_01_azuredeploy.parameters.json
There was a mismatch between VM size in the lab file and the json file with the parameters.
=> Updated VMSize parameter

Allfiles/Labfiles/Module_06/Network_Watcher/az-101-03b_01_azuredeploy.parameters.json
Update a VM size parameter from "Standard_DS1_v2" to "Standard_DS2_v2". The lab instruction says we should chose "Standard_DS2_v2".
=> Update a VM size parameter

Instructions/Labs/12 - Implementing File Sync (az-100-02b).md
+ Removed " - blob, file, table, queue" from "New" search for storage account
+ Changed "but" to "then" for clarity
=> Interface updates

Instructions/Labs/10 - Azure AD Identity Protection (az-101-04b).md
aaduser1
From
Directory role: **User**
To
Directory role: **Global administrator**
This is needed later on in the labs when activating Azure AD Identity Protection which requires Global administrator role for the current Azure Active Directory directory.
=> Update 10 - Azure AD Identity Protection (az-101-04b).md

Instructions/Labs/05 - VNet Peering and Service Chaining (az-100-04).md
Added some more detailed steps for configuring Routing and Remote access to step Module 5, Exercise 2, tasks 5 and 6.
=> Added detailed steps for configuring Routing

Instructions/Labs/07 - Implement ASR Between Regions (az-101-01).md
Highlighted separate region in Lab 7 ASR in ex 2 task 1 step 2
=> Highlighted separate region in ex 2 task 1 step 2

Allfiles/Labfiles/Module_02/Deploy_and_Manage_Virtual_Machines/az-100-03_azuredeploy.json
Changed VM size for best case scenario
=> Changed VM size for best case scenario

Instructions/Labs/02a - Deploy and Manage Virtual Machines (az-100-03).md
Bring more clarity on steps for SSH session on exercise 2 and Updating VM Scale Set instance on exercise 3
=> Update 02a - Deploy and Manage Virtual Machines (az-100-03).md

Instructions/Labs/07 - Implement ASR Between Regions (az-101-01).md
Missing step on line 127, click on replicate button
=> Update 07 - Implement ASR Between Regions (az-101-01).md

Instructions/Labs/12 - Implementing File Sync (az-100-02b).md
Just correcting the item name: From bad "Deploy Storage Sync" to correct "Deploy Azure File Sync", on points 5 + 6 Task 1, Ex.2
=> Update 12 - Implementing File Sync (az-100-02b).md

Instructions/Labs/03 - Implement and Manage Storage (az-100-02).md
Adding the -persist parameter is not required anymore as it is already included in the snippet provided by the Azure Portal.
=> Removed "adding -persist to the script"

Instructions/Labs/02a - Deploy and Manage Virtual Machines (az-100-03).md
Exercise 1, Task 3, Step 10, Virtual Network Resource Group: This resource group isn't new, it's referencing the group from Task 1, Step 5. Instructions are confusing to those attending training.
=> Update Exercise 1, Task 3, Step 10

Instructions/Labs/02a - Deploy and Manage Virtual Machines (az-100-03).md
Fixed cmdlet spelling Set-AzVMBootDiagnostic to Set-AzVMBootDiagnostics on Lab 2 task 2 step 9
=> Fixed cmdlet spelling Set-AzVMBootDiagnostic to Set-AzVMBootDiagnostics

Instructions/Labs/04 - Configure Azure DNS (az-100-04b).md
Task 1, Step 5 - removes redundant ‘to’.
=> Minor typo fix in DNS lab

Instructions/Labs/02a - Deploy and Manage Virtual Machines (az-100-03).md, Instructions/Labs/03 - Implement and Manage Storage (az-100-02).md, Instructions/Labs/04 - Configure Azure DNS (az-100-04b).md, Instructions/Labs/05 - VNet Peering and Service Chaining (az-100-04).md, Instructions/Labs/06 - Azure Network Watcher (az-101-03b).md, Instructions/Labs/07 - Implement ASR Between Regions (az-101-01).md, Instructions/Labs/08 - Load Balancer and Traffic Manager (az-101-03).md, Instructions/Labs/09 - Implement Directory Synchronization (az-100-05).md, Instructions/Labs/11a - Role-Based Access Control (az-100-01).md, Instructions/Labs/11b - Governance and Compliance (az-100-01b).md
"Create a resource" isn't a blade but a hub, changed the language to match the other instructions.
=> Removed references to 'Create a resource' to 'New'

Instructions/Labs/02a - Deploy and Manage Virtual Machines (az-100-03).md
Low Priority option, got removed.
=> Removed Low Priority

Instructions/Labs/02a - Deploy and Manage Virtual Machines (az-100-03).md, Instructions/Labs/03 - Implement and Manage Storage (az-100-02).md, Instructions/Labs/04 - Configure Azure DNS (az-100-04b).md, Instructions/Labs/05 - VNet Peering and Service Chaining (az-100-04).md, Instructions/Labs/06 - Azure Network Watcher (az-101-03b).md, Instructions/Labs/07 - Implement ASR Between Regions (az-101-01).md, Instructions/Labs/08 - Load Balancer and Traffic Manager (az-101-03).md, Instructions/Labs/09 - Implement Directory Synchronization (az-100-05).md, Instructions/Labs/11a - Role-Based Access Control (az-100-01).md, Instructions/Labs/11b - Governance and Compliance (az-100-01b).md
Reverts MicrosoftLearning/AZ-103-MicrosoftAzureAdministrator#226
=> Revert "Removed references to 'Create a resource' to 'New'"

Instructions/Labs/02a - Deploy and Manage Virtual Machines (az-100-03).md, Instructions/Labs/03 - Implement and Manage Storage (az-100-02).md, Instructions/Labs/04 - Configure Azure DNS (az-100-04b).md, Instructions/Labs/05 - VNet Peering and Service Chaining (az-100-04).md, Instructions/Labs/06 - Azure Network Watcher (az-101-03b).md, Instructions/Labs/07 - Implement ASR Between Regions (az-101-01).md, Instructions/Labs/08 - Load Balancer and Traffic Manager (az-101-03).md, Instructions/Labs/09 - Implement Directory Synchronization (az-100-05).md, Instructions/Labs/11a - Role-Based Access Control (az-100-01).md, Instructions/Labs/11b - Governance and Compliance (az-100-01b).md
Reverts MicrosoftLearning/AZ-103-MicrosoftAzureAdministrator#232
=> Revert "Revert "Removed references to 'Create a resource' to 'New'""

Instructions/Labs/02a - Deploy and Manage Virtual Machines (az-100-03).md
Fixed spacing and changed the code blocks to use **\`\`\`powershell** instead of **\`\`\`pwsh** (Current verion of pandoc cannot use the alias pwsh.)
=> UI changes in Mod 2 lab

Instructions/Labs/02a - Deploy and Manage Virtual Machines (az-100-03).md, Instructions/Labs/03 - Implement and Manage Storage (az-100-02).md, Instructions/Labs/04 - Configure Azure DNS (az-100-04b).md, Instructions/Labs/05 - VNet Peering and Service Chaining (az-100-04).md, Instructions/Labs/06 - Azure Network Watcher (az-101-03b).md, Instructions/Labs/07 - Implement ASR Between Regions (az-101-01).md, Instructions/Labs/08 - Load Balancer and Traffic Manager (az-101-03).md, Instructions/Labs/09 - Implement Directory Synchronization (az-100-05).md, Instructions/Labs/10a - Azure AD Identity Protection (az-101-04b).md
Spacing and indents for proper Pandoc formatting.
Change \`\`\`pwsh to \`\`\`powershell
=> UI changes

Instructions/Labs/02a - Deploy and Manage Virtual Machines (az-100-03).md, Instructions/Labs/06 - Azure Network Watcher (az-101-03b).md, Instructions/Labs/10a - Azure AD Identity Protection (az-101-04b).md
As an alternative to #237 , the template will work _IF_ we use (at least) a Standard_DS2_v2 size. (DSC to install IIS requires at least 2 vcores and 4 GB RAM.)
=> Fix some spacing, fix VM size in 02

Instructions/Labs/04 - Configure Azure DNS (az-100-04b).md, Instructions/Labs/06 - Azure Network Watcher (az-101-03b).md, Instructions/Labs/10a - Azure AD Identity Protection (az-101-04b).md, Instructions/Labs/10b - Self-Service Password Reset (az-100-05b).md, Instructions/Labs/11a - Role-Based Access Control (az-100-01).md, Instructions/Labs/11b - Governance and Compliance (az-100-01b).md, Instructions/Labs/12 - Implementing File Sync (az-100-02b).md
indents and powershell tags on code blocks.
On 12, changed size to DS2_v2 to eliminate crashing on startup of VM.
=> UI changes, formatting fixes for Pandoc

Allfiles/Labfiles/Module_12/Implementing_File_Sync/az-100-02b_azuredeploy.parameters.json, Instructions/Labs/12 - Implementing File Sync (az-100-02b).md
File Sync needed some steps added to be removed (Resource Group removal fails if not done.)
(Also changed the template file for DS2_v2 mentioned in last pull request.)
=> Update 12 - Needed removal steps added

Instructions/Labs/12 - Implementing File Sync (az-100-02b).md
This adds a fix for an issue a group of us encountered today during our training.
=> Fix for az module install error
